version: '3'

services:
  web:
    build: .
    ports:
      - "9527:9527"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      # - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bible_app
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bible_app
    ports:
      - "6001:5432"

volumes:
  postgres_data: