"""Add auto_login_pin to User model

Revision ID: b2a7f8c90d3e
Revises: ee478fa608a2
Create Date: 2025-05-15 10:22:33.423123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a7f8c90d3e'
down_revision = 'ee478fa608a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_login_pin', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auto_login_pin')

    # ### end Alembic commands ###