"""Add auto_login_token to User model

Revision ID: ee478fa608a2
Revises: f5072a8944c2
Create Date: 2025-05-08 15:05:27.913132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee478fa608a2'
down_revision = 'f5072a8944c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_login_token', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_auto_login_token'), ['auto_login_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_auto_login_token'))
        batch_op.drop_column('auto_login_token')

    # ### end Alembic commands ###
