"""Add chapter timestamps

Revision ID: f5072a8944c2
Revises: 
Create Date: 2025-04-26 16:23:01.706385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5072a8944c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapters_timestamps', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progresses', schema=None) as batch_op:
        batch_op.drop_column('chapters_timestamps')

    # ### end Alembic commands ###
